# Copyright 2026 Seth Dillingham
# SPDX-License-Identifier: Apache-2.0

PRODUCT := rewrap-markdown
VERSION := $(shell cat VERSION)
FILTER_NAME ?= Rewrap Markdown
FILTER_WIDTH ?= 70
RELEASE_BINARY := $(abspath .build/release/$(PRODUCT))
DIST_DIR := dist
ARCH := $(shell uname -m)
DIST_BINARY := $(DIST_DIR)/$(PRODUCT)-$(VERSION)-macos-$(ARCH)
DIST_PYTHON := $(DIST_DIR)/$(PRODUCT)-$(VERSION).py
DIST_BBEDIT_SWIFT := $(DIST_DIR)/Rewrap Markdown (Swift)
BBEDIT_FILTERS_DIR ?= $(shell osascript \
	-e 'tell application "BBEdit" to set allFolders to support folders' \
	-e 'set targetFolder to (|text filters| of allFolders)' \
	-e 'return POSIX path of targetFolder' 2>/dev/null)
INSTALLED_FILTER := $(BBEDIT_FILTERS_DIR)/$(FILTER_NAME)

.PHONY: build release test test-executable dist install uninstall clean print-bbedit-filters-dir

build:
	swift build

release:
	swift build -c release

test:
	swift test

test-executable: release
	REWRAP_MARKDOWN_EXECUTABLE="$(RELEASE_BINARY)" swift test

dist: test-executable
	mkdir -p "$(DIST_DIR)"
	cp "$(RELEASE_BINARY)" "$(DIST_BINARY)"
	cp Reference/rewrap_markdown.py "$(DIST_PYTHON)"
	cp "Distribution/BBEdit/Rewrap Markdown (Swift)" "$(DIST_BBEDIT_SWIFT)"
	chmod +x "$(DIST_BINARY)" "$(DIST_PYTHON)" "$(DIST_BBEDIT_SWIFT)"
	@echo "Created release artifacts in $(DIST_DIR):"
	@printf '  %s\n' "$(DIST_BINARY)" "$(DIST_PYTHON)" "$(DIST_BBEDIT_SWIFT)"

install: release
	@if [ -z "$(BBEDIT_FILTERS_DIR)" ]; then \
		echo "Could not determine BBEdit's Text Filters folder."; \
		echo "Set BBEDIT_FILTERS_DIR=/path/to/Text Filters and run make install again."; \
		exit 1; \
	fi
	mkdir -p "$(BBEDIT_FILTERS_DIR)"
	@{ \
		printf '%s\n' '#!/bin/sh'; \
		printf '%s\n' '# Generated by rewrap-markdown make install.'; \
		printf '%s\n' '# Edit this value to use a different BBEdit wrapping width, such as 80 or 120.'; \
		printf '%s\n' 'WRAP_WIDTH=$(FILTER_WIDTH)'; \
		printf '%s\n' 'if [ "$$#" -eq 0 ]; then'; \
		printf '%s\n' '	exec "$(RELEASE_BINARY)" "$$WRAP_WIDTH"'; \
		printf '%s\n' 'else'; \
		printf '%s\n' '	exec "$(RELEASE_BINARY)" "$$@"'; \
		printf '%s\n' 'fi'; \
	} > "$(INSTALLED_FILTER)"
	chmod +x "$(INSTALLED_FILTER)"
	@echo "Installed BBEdit text filter: $(INSTALLED_FILTER)"

uninstall:
	@if [ -z "$(BBEDIT_FILTERS_DIR)" ]; then \
		echo "Could not determine BBEdit's Text Filters folder."; \
		echo "Set BBEDIT_FILTERS_DIR=/path/to/Text Filters and run make uninstall again."; \
		exit 1; \
	fi
	rm -f "$(INSTALLED_FILTER)"
	@echo "Removed BBEdit text filter: $(INSTALLED_FILTER)"

clean:
	swift package clean

print-bbedit-filters-dir:
	@if [ -z "$(BBEDIT_FILTERS_DIR)" ]; then \
		echo "Could not determine BBEdit's Text Filters folder."; \
		exit 1; \
	fi
	@printf '%s\n' "$(BBEDIT_FILTERS_DIR)"
